#!/usr/bin/env bash

set -o pipefail
set -o errexit

export GIT_BRANCHDIR_DIR=$(dirname $0)
source "$GIT_BRANCHDIR_DIR/git-branchdir-common"

USAGE="\
Usage: git branchdir <subcommand>

Available subcommands are:
   new
   list
   merge
   publish
   move
   delete
   path

Try 'git branchdir <subcommand> --help' for details."
usage() {
    echo "$USAGE"
}

main() {
    SUBCOMMAND="$1"
    shift

    case $SUBCOMMAND in
        new|list|merge|publish|move|delete|path)
            ;;
        -h|--help)
            usage
            exit 0
            ;;
        *)
            usage
            exit 1
            ;;
    esac

    SUBCOMMAND_FILE="$GIT_BRANCHDIR_DIR/git-branchdir-$SUBCOMMAND"
    if [ ! -e "$SUBCOMMAND_FILE" ]; then
        usage
    else
        exec "$SUBCOMMAND_FILE" "$@"
    fi
}

main $@
