#!/usr/bin/env bash

set -o pipefail
set -o errexit

if [ $# -eq 0 ]; then
    set -- -h
fi

# git branch --help:
# git branch [--color[=<when>] | --no-color] [-r | -a]
#        [--list] [-v [--abbrev=<length> | --no-abbrev]]
#        [(--merged | --no-merged | --contains) [<commit>]] [<pattern>...]
# git branch [--set-upstream | --track | --no-track] [-l] [-f] <branchname> [<start-point>]
# git branch (-m | -M) [<oldbranch>] <newbranch>
# git branch (-d | -D) [-r] <branchname>...
# git branch --edit-description [<branchname>]

OPTIONS_SPEC="\
git branchdir -m [<oldbranch>] <newbranch>
git branchdir -d <branchname>...
git branchdir <branchname> [<start-point>]
--
h,help  show the help
m       move (rename) the branchdir
d       delete the branchdir
debug   enable debug messages
"
source "$(git --exec-path)/git-sh-setup"

ACTION=new
DEBUG=

while [ $# -gt 0 ]; do
    opt="$1"
    shift
    case "$opt" in
        --debug) DEBUG=1 ;;
        -d) ACTION=delete ;;
        -m) ACTION=move ;;
        --) break ;;
         *) usage ;;
    esac
done

if [ -n "$DEBUG" ]; then
    echo "Arguments: $*"
fi

branchdir_basedir() {
    if [ $# -eq 0 ]; then
        git config branchdir.base
    else
        git config --add branchdir.base "$1"
    fi
}

branchdir_delete() {
    branchname="$1"
    BASEDIR=$(branchdir_basedir)
    BRANCH_DIR="$BASEDIR/$branchname"
    git branch -d "$branchname"
    cd "$BASEDIR"
    rm -rf "$BRANCH_DIR"
}

branchdir_move() {
    oldbranch="$1"
    newbranch="$2"
    BASEDIR=$(branchdir_basedir)
    OLD_BRANCH_DIR="$BASEDIR/$oldbranch"
    NEW_BRANCH_DIR="$BASEDIR/$newbranch"
    git branch -m "$1" "$2"
    mv "$OLD_BRANCH_DIR" "$NEW_BRANCH_DIR"
}

branchdir_new() {
    branchname="$1"
    startpoint="$2"
    BASEDIR=$(branchdir_basedir)
    BRANCH_DIR="$BASEDIR/$branchname"
    git branch "$branchname" "$startpoint"
    git-new-workdir "$BASEDIR" "$BRANCH_DIR" "$branchname"
    cd "$BRANCH_DIR"
}

case "$ACTION" in
    delete)
        case $# in
            1) branchname="$1" ;;
            *) usage ;;
        esac
        branchdir_delete "$branchname"
        ;;
    move)
        case $# in
            2)  oldbranch="$1"
                newbranch="$2"
                ;;
            1)  oldbranch="<current_branch>"
                newbranch="$1"
                ;;
            0)  die "Missing required argument" ;;
            *)  die "Too many arguments" ;;
        esac
        branchdir_move "$oldbranch" "$newbranch"
        ;;
    new)
        case $# in
            2)  branchname="$1"
                startpoint="$2"
                ;;
            1)  branchname="$1"
                startpoint="HEAD"
                ;;
            0)  die "Missing required argument" ;;
            *)  die "Too many arguments" ;;
        esac
        if [ -z "$(branchdir_basedir)" ]; then
            branchdir_basedir "$(git rev-parse --show-toplevel)"
        fi
        branchdir_new "$branchname" "$startpoint"
        ;;
esac
