#!/usr/bin/env bash

set -o pipefail
set -o errexit

export GIT_BRANCHDIR_DIR=$(dirname $0)
source "$GIT_BRANCHDIR_DIR/git-branchdir-common"

OPTIONS_SPEC="\
git-branchdir new <branchname> [<startpoint>]
--
h,help  show the help
track   track remote startpoint
"
source "$GIT_CORE_DIR/git-sh-setup"

args=("$@")
for (( i = 0 ; i < ${#args[@]} ; i++ )) do
    if [ "${args[$i]}" == "--" ]; then
        SPLIT=$i
    fi
done
OPTS=(${args[@]:0:$SPLIT})
ARGS=(${args[@]:$(( $SPLIT + 1 ))})

if [ -z "$(branchdir_basedir)" ]; then
    die "Please run `git branchdir init` to configure before use."
fi
if [ ${#ARGS[@]} -lt 1 ]; then
    die "Must provide a branch name."
fi
branchname=${ARGS[0]}
git branch "$@"
git-new-workdir "$(branchdir_basedir)" "$(branchdir_path $branchname)" "$branchname"
register_branchdir $branchname
echo "New branchdir: $(branchdir_path $branchname)"
